<?php
function getStateCode()
{
$stateCode = array(1=> "Ajaokuta" ,
"G.R.A",
"Old G.R.A",
"Cantonment",
"Housing Estate",
"Kpata",
"Lokongoma",
"Phase 1",
"Barracks",
"Natako",
"Felele",
"IBB Way",
"ALiyu Attah Road",
"Zone 8",
"Gadumo",
"Lokoja Town Club",
"Adankolo",
"Govt House Road",
"Gannaja");
return $stateCode;
}
function getStateName()
{
$stateName = array(1=> "Ajaokuta",
"G.R.A",
"Old G.R.A",
"Cantonment",
"Housing Estate",
"Kpata",
"Lokongoma",
"Phase 1",
"Barracks",
"Natako",
"Felele",
"IBB Way",
"ALiyu Attah Road",
"Zone 8",
"Gadumo",
"Lokoja Town Club",
"Adankolo",
"Govt House Road",
"Gannaja");
return $stateName;
}
?>